---
title: "Client Report - BYU-Idaho Players and Comparing Teams"
subtitle: "Unit 2 Task 2"
author: "Zach McLaughlin"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd 
import numpy as np
import sqlite3
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
sqlite_file = 'lahmansbaseballdb.sqlite'
# this file must be in the same location as your .qmd or .py file
con = sqlite3.connect(sqlite_file)
```

## QUESTION 1

__Write an SQL query to create a new dataframe about baseball players who attended BYU-Idaho. The new table should contain five columns: playerID, schoolID, salary, and the yearID/teamID associated with each salary. Order the table by salary (highest to lowest) and print out the table in your report.__

Table shows that there were 2 players with that went to BYUI with the most earning in their careers being 400k down to the minimum of 150k.

```{python}
q = '''
  SELECT 
    s.playerID,
    c.schoolID,
    s.salary,
    s.yearID,
    s.teamID
  FROM 
    Salaries s
  JOIN 
    CollegePlaying c ON s.playerID = c.playerID
  WHERE 
    c.schoolID = 'idbyuid'
  ORDER BY 
    s.salary DESC;
  '''
results = pd.read_sql_query(q, con)
results
```


## QUESTION 2

__Pick any two baseball teams and compare them using a metric of your choice (average salary, home runs, number of wins, etc). Be creative! Write an SQL query to get the data you need, then make a graph using Lets-Plot to visualize the comparison. What do you learn?__ 

This table compares the average salary between the yankees and athletics over time

```{python}
q = '''
    SELECT 
      teamID,
      yearID,
      AVG(salary) AS avg_salary
    FROM 
      Salaries
    WHERE 
      teamID IN ('NYA', 'OAK')
    GROUP BY 
      teamID, yearID
    ORDER BY 
      yearID;
    '''
results = pd.read_sql_query(q, con)
results
```


```{python}
(
ggplot(results, aes(x='yearID', y='avg_salary', color='teamID'))
  + geom_line(size=1.5)
  + geom_point()
  + ggtitle("Average Salary Over Time: Yankees vs. Athletics")
  + xlab("Year") + ylab("Average Salary (USD)")
  + theme_minimal()
)
```