---
title: "Client Report - Famous Names"
subtitle: "Unit 1 Task 3"
author: "Zachary McLaughlin"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")
```



## QUESTION 1

<!-- Make sure at least one of your charts includes reference marks!! -->

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names in a single chart. What trends do you notice? You must provide a chart. The years labels on your charts should not include a comma.__ 

These names all peaked in popularity in the 50s and in the 70s all leveled still not being uncommon.

```{python}
# Q1
famouseNames = (df.query("name in ['Mary', 'Martha', 'Peter', 'Paul'] and 1920 <= year <= 2000"))

famouseNames
```

```{python}
# graph
(
ggplot(data = famouseNames,
  mapping = aes(x='year', y='Total', color='name'))
  + geom_line()
  + scale_x_continuous(format='')
)
```

## QUESTION 2

1. __Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage? You must provide a chart. The years labels on your charts should not include a comma.__  

I chose Marty due to Marty McFly from back to the future which origionally came out in 1985. The unpopular name peaked in the 60s was allready on the come down when the movie came it only only continued to sit low nearly nobody named marty by the year 2000 

```{python}
# Q2
movieName = (df.query("name == 'Marty'"))

(
ggplot(data = movieName,
  mapping = aes(x='year', y='Total'))
  + geom_line()
  + scale_x_continuous(format='')
  + geom_vline(xintercept=1962.5)
  + geom_text(x=1991, y=1320, label='Number of people named Marty peaked', color='black', size=7)
)
```


